#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/truckSceneG.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-i586.jar:$APPDIR/lib/gluegen-rt-natives-linux-i586.jar:$APPDIR/lib/serial.jar:$APPDIR/lib/jssc.jar:$APPDIR/lib/gstreamer-java.jar:$APPDIR/lib/video.jar:$APPDIR/lib/jna.jar:$APPDIR/lib/sound.jar" truckSceneG "$@"
